#declaring empty list to save twin prime numbers 
twin_primes = []

#loop iterating over numbers starting from 3 as we wangt odd numbers only 
#step size 2 ensures that only odd numbers will be generated by range
for num in range(3,1000,2):
	for i in range(2,int(num/2)+2):
		if num%i == 0 or (num+2)%i == 0:
			break	
	else:
		twin_primes.append((num,num+2))

print("Twin primes less than 1000 are")
for a,b in twin_primes:
	print(a,b)